// import { BalanceInfo } from './types';
import en from '../i18n/en';
import { Storage, TokenApiInfo } from './types';

export const i18nDict = { en };

// export const PROD = process.env.NODE_ENV === 'production';

export const defaultStorage: Omit<Storage, 'encryptedSecrets' | 'accountList'> = {
	language: 'en',
	activeNetworkIndex: 0,
	networkList: [
		{
			name: 'Mainnet',
			rpcUrl: 'wss://node.vite.net/gvite/ws',
			// http: 'https://node.vite.net/gvite',
			explorerUrl: 'https://vitescan.io',
		},
		{
			name: 'Testnet',
			rpcUrl: 'wss://buidl.vite.net/gvite/ws',
			// http: 'https://buidl.vite.net/gvite',
			explorerUrl: 'https://test.vitescan.io',
		},
		{
			name: 'Localnet',
			rpcUrl: 'ws://localhost:23457',
			// http: 'http://127.0.0.1:23456',
		},
	],
	currencyConversion: 'USD',
	activeAccountIndex: 0,
	contacts: {},
	displayedTokenIdsAndNames: [['tti_5649544520544f4b454e6e40', 'vite']],
	connectedDomains: {},
};

export const ExplorerURLs = {
	vitescan: {
		mainnet: {
			home: 'https://vitescan.io/',
			address: 'https://vitescan.io/address/',
			hash: 'https://vitescan.io/tx/',
			token: 'https://vitescan.io/token/',
		},
		testnet: {
			home: 'https://test.vitescan.io/',
			address: 'https://test.vitescan.io/address/',
			hash: 'https://test.vitescan.io/tx/',
			token: 'https://test.vitescan.io/token/',
		},
	},
	viteview: {
		mainnet: {
			home: 'https://mainnet.viteview.xyz/#/',
			address: 'https://mainnet.viteview.xyz/#/account/',
			hash: 'https://mainnet.viteview.xyz/#/snapshot/',
			token: 'https://mainnet.viteview.xyz/#/token/',
		},
		testnet: {
			home: 'https://buidl.viteview.xyz/#/',
			address: 'https://buidl.viteview.xyz/#/account/',
			hash: 'https://buidl.viteview.xyz/#/snapshot/',
			token: 'https://buidl.viteview.xyz/#/token/',
		},
	},
	// vitetxs: {
	// 	home: 'https://vitetxs.de/#/',
	// 	address: '',
	// 	hash: '',
	// 	token: '',
	// },
	// VITCScan: {
	// 	mainnet: {
	// 		home: 'https://vitcscan.com/',
	// 		address: 'https://vitcscan.com/address/',
	// 		hash: 'https://vitcscan.com/tx/',
	// 		token: 'https://vitcscan.com/token/',
	// 	},
	// },
	// vitexplorer: {
	// 	mainnet: {
	// 		home: 'https://vitexplorer.fr/dashboard',
	// 		address: 'https://vitexplorer.fr/address/',
	// 		hash: 'https://vitexplorer.fr/transaction/',
	// 		token: 'https://vitexplorer.fr/token/',
	// 	},
	// },
};

export const currencyConversions = [
	'USD',
	// 'AUD',
	// 'BTC',
	// 'CAD',
	// 'EUR',
	// 'HKD',
	// 'INR',
	// 'IDR',
	// 'XMR',
	// 'NZD',
	// 'PHP',
	// 'RUB',
	// 'SGD',
] as const;

export const languages: { [key in keyof typeof i18nDict]: string } = {
	// stored as an object for easier lookups. The language is stored in the shorthand version cuz they're filename friendly, but displayed in longhand for readability
	en: 'English',
};

// export const testnetTokenList = [
// 	['VITE', 'tti_5649544520544f4b454e6e40']
// ]

// export const defaultTokenList = [
// 	['VITE', 'tti_5649544520544f4b454e6e40'],
// 	['BNB', 'tti_fb901364ef662c25cf43125c'],
// 	['BTC', 'tti_b90c9baffffc9dae58d1f33f'],
// 	['BUSD', 'tti_c8c9ad17bc7b45e38eb88a44'],
// 	['DAI', 'tti_c90c146c059b821527f40b98'],
// 	['EPIC', 'tti_f370fadb275bc2a1a839c753'],
// 	['ETH', 'tti_687d8a93915393b219212c73'],
// 	['NANO', 'tti_29a2af20212b985e9d49e899'],
// 	['UNI', 'tti_34c5ed639f97d1e826451c92'],
// 	['USDC', 'tti_7fb89970f021269b6e101be1'],
// 	['USDT', 'tti_80f3751485e4e83456059473'],
// 	['VUILD', 'tti_f1fdb1fce23ca4a2c760012c'],
// 	['VX', 'tti_564954455820434f494e69b5'],
// 	['XLM', 'tti_181e08c4fdb2876956245076'],
// 	['XMR', 'tti_e5750d3c5b3bb5a31b8ba637'],
// ];

export const defaultTokenList: TokenApiInfo[] = [
	{
		symbol: 'VITE',
		name: 'VITE',
		tokenCode: '1171',
		platform: 'VITE',
		tokenAddress: 'tti_5649544520544f4b454e6e40',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/e6dec7dfe46cb7f1c65342f511f0197c.png',
		decimal: 18,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'VITE',
				name: 'ViteToken',
				tokenCode: '1564',
				platform: 'ETH',
				tokenAddress: '0xadd5E881984783dD432F80381Fb52F45B53f3e70',
				standard: 'ERC20',
				url: 'https://crosschain.vite.net/gateway/eth',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/e6dec7dfe46cb7f1c65342f511f0197c.png',
				decimal: 18,
				mappedTokenExtras: [
					{
						symbol: 'VITE',
						name: null,
						tokenCode: '1588',
						platform: 'BSC',
						tokenAddress: '0x2794dad4077602ed25a88d03781528d1637898b4',
						standard: 'BEP20',
						url: 'https://crosschain.vite.net/gateway/bsc',
						tokenIndex: null,
						icon: 'https://static.vite.net/token-profile-1257137467/icon/e6dec7dfe46cb7f1c65342f511f0197c.png',
						decimal: 18,
						mappedTokenExtras: null,
					},
				],
			},
			url: 'https://crosschain.vite.net/gateway/eth',
		},
	},
	{
		symbol: 'BNB',
		name: 'Binance Coin',
		tokenCode: '1595',
		platform: 'VITE',
		tokenAddress: 'tti_fb901364ef662c25cf43125c',
		standard: null,
		url: null,
		tokenIndex: 1,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/ac0b3141eb601e8c3ff78397bcc25672.png',
		decimal: 18,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'BNB',
				name: null,
				tokenCode: '1600',
				platform: 'BSC',
				tokenAddress: null,
				standard: 'BEP20',
				url: 'https://crosschain.vite.net/gateway/bsc',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/ac0b3141eb601e8c3ff78397bcc25672.png',
				decimal: 18,
				mappedTokenExtras: null,
			},
			url: 'https://crosschain.vite.net/gateway/bsc',
		},
	},
	{
		symbol: 'BTC',
		name: 'Bitcoin',
		tokenCode: '1351',
		platform: 'VITE',
		tokenAddress: 'tti_b90c9baffffc9dae58d1f33f',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/7b04d1b14726fa3c20aa32daa946366f.png',
		decimal: 8,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'BTC',
				name: 'Bitcoin',
				tokenCode: '3',
				platform: 'BTC',
				tokenAddress: null,
				standard: '',
				url: 'https://crosschain.vite.net/gateway/btc',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/7b04d1b14726fa3c20aa32daa946366f.png',
				decimal: 8,
				mappedTokenExtras: null,
			},
			url: 'https://crosschain.vite.net/gateway/btc',
		},
	},
	{
		symbol: 'BUSD',
		name: 'Binance USD',
		tokenCode: '1435',
		platform: 'VITE',
		tokenAddress: 'tti_c8c9ad17bc7b45e38eb88a44',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/4d3c6cdb125ca4fad91c25b924d89952.png',
		decimal: 18,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'BUSD',
				name: null,
				tokenCode: '1437',
				platform: 'ETH',
				tokenAddress: '0x4Fabb145d64652a948d72533023f6E7A623C7C53',
				standard: 'ERC20',
				url: 'https://crosschain.vite.net/gateway/eth',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/4d3c6cdb125ca4fad91c25b924d89952.png',
				decimal: 18,
				mappedTokenExtras: [
					{
						symbol: 'BUSD',
						name: null,
						tokenCode: '1591',
						platform: 'BSC',
						tokenAddress: '0xe9e7cea3dedca5984780bafc599bd69add087d56',
						standard: 'BEP20',
						url: 'https://crosschain.vite.net/gateway/bsc',
						tokenIndex: null,
						icon: 'https://static.vite.net/token-profile-1257137467/icon/4d3c6cdb125ca4fad91c25b924d89952.png',
						decimal: 18,
						mappedTokenExtras: null,
					},
				],
			},
			url: 'https://crosschain.vite.net/gateway/eth',
		},
	},
	{
		symbol: 'DAI',
		name: 'Dai',
		tokenCode: '1527',
		platform: 'VITE',
		tokenAddress: 'tti_c90c146c059b821527f40b98',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/3c231a8309999ad226afa097488a6158.png',
		decimal: 18,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'DAI',
				name: null,
				tokenCode: '1533',
				platform: 'ETH',
				tokenAddress: '0x6b175474e89094c44da98b954eedeac495271d0f',
				standard: 'ERC20',
				url: 'https://crosschain.vite.net/gateway/eth',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/3c231a8309999ad226afa097488a6158.png',
				decimal: 18,
				mappedTokenExtras: null,
			},
			url: 'https://crosschain.vite.net/gateway/eth',
		},
	},
	{
		symbol: 'EPIC',
		name: 'Epic Cash',
		tokenCode: '1569',
		platform: 'VITE',
		tokenAddress: 'tti_f370fadb275bc2a1a839c753',
		standard: null,
		url: null,
		tokenIndex: 2,
		icon: 'https://static.vite.net/crypto-info/tokens/epic/tti_f370fadb275bc2a1a839c753.png',
		decimal: 8,
		gatewayInfo: {
			name: 'VGATE',
			icon: 'https://static.vite.net/token-profile-1257137467/icon/eb74a50d9a17e5ba1c2e0c27c531efc4.png',
			policy: {
				en: 'https://vgate.io/clause',
			},
			overview: {
				en: "As an operator of ViteX, VGATE is responsible for listing coins, deposit and withdrawal, cryptocurrency marketing and promoting and other services within VGATE's own marketing area.VGATE has complete capabilities as an operator, namely the capabilities of operating VGATE and its cryptos. In addition to helping users list cryptos, deposit and withdraw, and adjust transaction fees, VGATE can also mint coins, help other operators mint coins and run their gateways.",
			},
			links: {
				website: ['https://vgate.io/'],
				email: ['vgateservice@gmail.com'],
			},
			support: 'vgateservice@gmail.com',
			serviceSupport: 'https://vgate.zendesk.com/hc/en-us/requests/new',
			isOfficial: true,
			level: 2,
			website: 'https://vgate.io/',
			mappedToken: {
				symbol: 'EPIC',
				name: null,
				tokenCode: '1461',
				platform: 'EPIC',
				tokenAddress: null,
				standard: '',
				url: 'https://gateway.vgate.io/gateway/epic',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/8a393174e7e5766c33dba77c2b770f9d.png',
				decimal: 8,
				mappedTokenExtras: null,
			},
			url: 'https://gateway.vgate.io/gateway/epic',
		},
	},
	{
		symbol: 'ETH',
		name: 'Ethereum',
		tokenCode: '1352',
		platform: 'VITE',
		tokenAddress: 'tti_687d8a93915393b219212c73',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/4260d31a557c9084bdaef65d15cec36d.png',
		decimal: 18,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'ETH',
				name: 'Ether',
				tokenCode: '1',
				platform: 'ETH',
				tokenAddress: null,
				standard: '',
				url: 'https://crosschain.vite.net/gateway/eth',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/4260d31a557c9084bdaef65d15cec36d.png',
				decimal: 18,
				mappedTokenExtras: null,
			},
			url: 'https://crosschain.vite.net/gateway/eth',
		},
	},
	{
		symbol: 'NANO',
		name: 'Nano',
		tokenCode: '1593',
		platform: 'VITE',
		tokenAddress: 'tti_29a2af20212b985e9d49e899',
		standard: null,
		url: null,
		tokenIndex: 1,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/tti_29a2af20212b985e9d49e899.png',
		decimal: 30,
		gatewayInfo: {
			name: 'ViNo',
			icon: 'https://static.vite.net/token-profile-1257137467/icon/tti_cdf7c68ea377f663ee11d234.png',
			policy: {
				en: 'https://github.com/ViNo-community/ViNo-Custodial-Gateway/blob/main/TOS',
			},
			overview: {
				en: 'ViNo Gateway runs cross-chain services for various cryptocurrencies on Vitex',
				zh: 'ViNo Gateway runs cross-chain services for various cryptocurrencies on Vitex',
			},
			links: {
				website: ['https://twitter.com/nanogateorg'],
				github: ['https://github.com/ViNo-community'],
				twitter: ['https://twitter.com/nanogateorg'],
				whitepaper: ['https://forum.vite.net/topic/4745/introduction-of-vitex-operator-vino/'],
				discord: ['https://t.co/lm3GpFXzoZ?amp=1'],
				explorer: ['https://explorer.vite.net'],
				reddit: ['https://www.reddit.com/user/ViNo_Community'],
				email: ['nanocommunityoperator@gmail.com'],
			},
			support: 'nanocommunityoperator@gmail.com',
			serviceSupport: 'https://twitter.com/nanogateorg',
			isOfficial: false,
			level: 0,
			website: 'https://twitter.com/nanogateorg',
			mappedToken: {
				symbol: 'NANO',
				name: null,
				tokenCode: '1594',
				platform: 'NANO',
				tokenAddress: null,
				standard: '',
				url: 'https://patrola.me/gateways/nano',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/tti_29a2af20212b985e9d49e899.png',
				decimal: 30,
				mappedTokenExtras: null,
			},
			url: 'https://patrola.me/gateways/nano',
		},
	},
	{
		symbol: 'UNI',
		name: 'Uniswap',
		tokenCode: '1715',
		platform: 'VITE',
		tokenAddress: 'tti_34c5ed639f97d1e826451c92',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/crypto-info/tokens/UNI/tti_34c5ed639f97d1e826451c92.png',
		decimal: 18,
		gatewayInfo: {
			name: 'XGate',
			icon: 'https://static.vite.net/crypto-info/gateways/XGate/XGate.png',
			policy: {
				en: 'https://github.com/ViNo-community/ViNo-Custodial-Gateway/blob/main/TOS',
			},
			overview: {
				en: 'XGate runs cross-chain services for various cryptocurrencies on Vitex',
				zh: 'XGate runs cross-chain services for various cryptocurrencies on Vitex',
			},
			links: {
				website: ['https://twitter.com/xgatevite'],
				github: ['https://github.com/ViNo-community'],
				twitter: ['https://twitter.com/xgatevite'],
				discord: ['https://t.co/lm3GpFXzoZ?amp=1'],
				explorer: ['https://explorer.vite.net'],
				email: ['xgatevite@gmail.com'],
			},
			support: 'xgatevite@gmail.com',
			serviceSupport: 'https://twitter.com/xgatevite',
			isOfficial: false,
			level: 0,
			website: 'https://twitter.com/xgatevite',
			mappedToken: {
				symbol: 'UNI',
				name: null,
				tokenCode: '1717',
				platform: 'ETH',
				tokenAddress: '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984',
				standard: 'ERC20',
				url: 'https://patrola.me/gateways/eth',
				tokenIndex: null,
				icon: 'https://static.vite.net/crypto-info/tokens/UNI/tti_34c5ed639f97d1e826451c92.png',
				decimal: 18,
				mappedTokenExtras: null,
			},
			url: 'https://patrola.me/gateways/eth',
		},
	},
	{
		symbol: 'USDC',
		name: 'USD Coin',
		tokenCode: '1528',
		platform: 'VITE',
		tokenAddress: 'tti_7fb89970f021269b6e101be1',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/5faa1fa2b952137081e36c51af2b493c.png',
		decimal: 6,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'USDC',
				name: 'USD Coin',
				tokenCode: '267',
				platform: 'ETH',
				tokenAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
				standard: 'ERC20',
				url: 'https://crosschain.vite.net/gateway/eth',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/5faa1fa2b952137081e36c51af2b493c.png',
				decimal: 6,
				mappedTokenExtras: null,
			},
			url: 'https://crosschain.vite.net/gateway/eth',
		},
	},
	{
		symbol: 'USDT',
		name: 'Tether USD',
		tokenCode: '1353',
		platform: 'VITE',
		tokenAddress: 'tti_80f3751485e4e83456059473',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/c746e8a95dff8ce193c462554feb61bf.png',
		decimal: 6,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'USDT',
				name: 'Tether USD',
				tokenCode: '286',
				platform: 'ETH',
				tokenAddress: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
				standard: 'ERC20',
				url: 'https://crosschain.vite.net/gateway/eth',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/c746e8a95dff8ce193c462554feb61bf.png',
				decimal: 6,
				mappedTokenExtras: [
					{
						symbol: 'USDT',
						name: null,
						tokenCode: '1562',
						platform: 'BSC',
						tokenAddress: '0x55d398326f99059ff775485246999027b3197955',
						standard: 'BEP20',
						url: 'https://crosschain.vite.net/gateway/bsc',
						tokenIndex: null,
						icon: 'https://static.vite.net/token-profile-1257137467/icon/c746e8a95dff8ce193c462554feb61bf.png',
						decimal: 6,
						mappedTokenExtras: null,
					},
				],
			},
			url: 'https://crosschain.vite.net/gateway/eth',
		},
	},
	{
		symbol: 'VUILD',
		name: 'Vite Builder DAO Token',
		tokenCode: '1611',
		platform: 'VITE',
		tokenAddress: 'tti_f1fdb1fce23ca4a2c760012c',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/tti_f1fdb1fce23ca4a2c760012c.png',
		decimal: 18,
		gatewayInfo: null,
	},
	{
		symbol: 'VX',
		name: 'ViteX Coin',
		tokenCode: '1298',
		platform: 'VITE',
		tokenAddress: 'tti_564954455820434f494e69b5',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/da32251cdc6b4e88963523659d705b83.png',
		decimal: 18,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'VX',
				name: null,
				tokenCode: '1630',
				platform: 'BSC',
				tokenAddress: '0xbbdac6ca30ba9189c7bf67a1f7160379f7e25835',
				standard: 'BEP20',
				url: 'https://crosschain.vite.net/gateway/bsc',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/da32251cdc6b4e88963523659d705b83.png',
				decimal: 18,
				mappedTokenExtras: null,
			},
			url: 'https://crosschain.vite.net/gateway/bsc',
		},
	},
	{
		symbol: 'XLM',
		name: 'Stellar',
		tokenCode: '1637',
		platform: 'VITE',
		tokenAddress: 'tti_181e08c4fdb2876956245076',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/crypto-info/tokens/XLM/tti_181e08c4fdb2876956245076.png',
		decimal: 7,
		gatewayInfo: {
			name: 'XGate',
			icon: 'https://static.vite.net/crypto-info/gateways/XGate/XGate.png',
			policy: {
				en: 'https://github.com/ViNo-community/ViNo-Custodial-Gateway/blob/main/TOS',
			},
			overview: {
				en: 'XGate runs cross-chain services for various cryptocurrencies on Vitex',
				zh: 'XGate runs cross-chain services for various cryptocurrencies on Vitex',
			},
			links: {
				website: ['https://twitter.com/xgatevite'],
				github: ['https://github.com/ViNo-community'],
				twitter: ['https://twitter.com/xgatevite'],
				discord: ['https://t.co/lm3GpFXzoZ?amp=1'],
				explorer: ['https://explorer.vite.net'],
				email: ['xgatevite@gmail.com'],
			},
			support: 'xgatevite@gmail.com',
			serviceSupport: 'https://twitter.com/xgatevite',
			isOfficial: false,
			level: 0,
			website: 'https://twitter.com/xgatevite',
			mappedToken: {
				symbol: 'XLM',
				name: null,
				tokenCode: '1639',
				platform: 'XLM',
				tokenAddress: null,
				standard: '',
				url: 'https://patrola.me/gateways/xlm',
				tokenIndex: null,
				icon: 'https://static.vite.net/crypto-info/tokens/XLM/tti_181e08c4fdb2876956245076.png',
				decimal: 7,
				mappedTokenExtras: null,
			},
			url: 'https://patrola.me/gateways/xlm',
		},
	},
	{
		symbol: 'XMR',
		name: 'Monero',
		tokenCode: '1488',
		platform: 'VITE',
		tokenAddress: 'tti_e5750d3c5b3bb5a31b8ba637',
		standard: null,
		url: null,
		tokenIndex: 0,
		icon: 'https://static.vite.net/token-profile-1257137467/icon/853604c1c1a6fdae4fa463c200a98c85.png',
		decimal: 12,
		gatewayInfo: {
			name: 'Vite Gateway',
			icon: null,
			policy: {
				en: 'https://x.vite.net/viteLabsGatePrivacy.html',
			},
			overview: {
				en: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
				zh: 'Vite Gateway runs cross-chain services for four coins: BTC, ETH, USDT(ERC20)',
			},
			links: {
				website: ['https://vite.org'],
				whitepaper: ['https://github.com/vitelabs/whitepaper/'],
				explorer: ['https://explorer.vite.net'],
				email: ['gateway@vite.org'],
			},
			support: 'gateway@vite.org',
			serviceSupport: 'https://vitex.zendesk.com/hc/en-001/requests/new',
			isOfficial: false,
			level: 0,
			website: 'https://vite.org',
			mappedToken: {
				symbol: 'XMR',
				name: null,
				tokenCode: '1489',
				platform: 'XMR',
				tokenAddress: null,
				standard: '',
				url: 'https://crosschain.vite.net/gateway/monero',
				tokenIndex: null,
				icon: 'https://static.vite.net/token-profile-1257137467/icon/853604c1c1a6fdae4fa463c200a98c85.png',
				decimal: 12,
				mappedTokenExtras: null,
			},
			url: 'https://crosschain.vite.net/gateway/monero',
		},
	},
];
